INSERT INTO category (name)
    VALUES ('Comidas'),
           ('Bebidas'),
           ('Eletronicos'),
           ('Vestuarios'),
           ('Joias e Relogios'),
           ('Brinquedos');
INSERT INTO product (title, price, description, image, category_id)
    VALUES ('Mouse', 20.00, 'Mouse óptico sem fio com receptor USB Nano, 2.4G', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/mouse-sem-fio-removebg-preview.png?raw=true', 3),
           ('Teclado', 30, 'Teclado Wireless', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/teclado-wiriless.png?raw=true', 3),
           ('Camiseta', 50, 'Camiseta Lacoste', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/camiseta-lacoste-removebg-preview.png?raw=true', 4),
           ('Colar de Jade', 200, 'Colar com pedras de jade', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/colar-com-pedra-de-jade.png?raw=true', 5),
           ('Buzz Lightyear', 30, 'Boneco Buzz Lightyear', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/boneco-buzz-removebg-preview.png?raw=true', 6),
           ('Vinho Cantinho do Vale', 10, 'Vinho Cantinho do Vale', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/vinho-cantinho-do-vale-removebg-preview.png?raw=true', 2),
           ('Barbie Fashion', 39.9, 'Barbie Original Unidade Modelos Variados', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/barbie-removebg-preview.png?raw=true', 6),
           ('Smartwatch Amazfit', 799, ' Smartwatch Amazfit com caixa 46.5mm de liga de alumínio pulseira obsidian black de silicone A2023', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/relogio-amazonfit-removebg-preview.png?raw=true', 5),
           ('Blusa Plus Size', 55, ' Blusa Plus Size Manga Longa Ampla Feminina', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/plus-size-removebg-preview.png?raw=true', 4),
           ('Drone Ryze', 674, ' Drone Ryze DJI com câmera HD branco 2.4GHz', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/drone-dji-mavic-2-pro-fly-more-combo-removebg-preview.png?raw=true', 3),
           ('Receptor Digital', 378.31, 'Receptor Digital Century Midiabox Azul Hd Tv Midia Box B4', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/receptor-digital-removebg-preview.png?raw=true', 3),
           ('Smart Tv Led 40 Philco', 1829, 'Smart Tv Led 40 Philco  Full Hd Com Wi-fi', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/smart-tv-removebg-preview.png?raw=true', 3),
           ('Ballantine', 78.9, 'Ballantine Blended Finest 1 L', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/ballantines-finest-removebg-preview.png?raw=true', 2),
           ('Whisky Black Label', 139.56, 'Whisky Black Label 1 Litro Johnnie Walker', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/black-label-removebg-preview.png?raw=true', 2),
           ('Bolinho De Laranja', 1.39, ' Bolinho De Laranja Bauducco 30g', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/bolinho_pleno_laranja-removebg-preview.png?raw=true', 1),
           ('Café Torrado 3 Corações', 16.46, 'Café Moído Tradicional 3 Corações 500g', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/cafe-torrado-removebg-preview.png?raw=true', 1),
           ('Chocottone Bauducco', 37.99, '  Chocottone Bauducco 908g', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/panettone-bauducco-removebg-preview.png?raw=true', 1),
           ('Leite Condensado', 5.89, ' Leite Condensado Integral Moça Nestlé Lata 395g', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/leite-moca-removebg-preview.png?raw=true', 1),
           ('Doritos Queijo Nacho', 5.49, 'Doritos queijo nacho 84g', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/doritos-queijo-nacho-removebg-preview.png?raw=true', 1),
           ('Vodka Smirnoff ', 34.9, 'Vodka Smirnoff 998ml', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/vodka-smirnoff-removebg-preview.png?raw=true', 2),
           ('Vodka Absolut', 76.9, '1 Litro', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/vodka-absolut-removebg-preview.png?raw=true', 2),
           ('Boneco Baby Yoda', 280.34, 'Pelúcia Mattel Star Wars The Mandalorian ', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/boneco-baby-yoda-removebg-preview.png?raw=true', 6),
           ('Loom Band', 22.47, 'Pulseirinhas - Liguinha - Kit Completo ', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/Loom-Band-removebg-preview.png?raw=true', 6),
           ('Maleta Médico Infantl', 80.1, 'Mochila Doctor Little - Replaykids ', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/maleta-infantil-removebg-preview.png?raw=true', 6),
           ('Colar E Brinco', 78, 'Conjunto Colar E Brinco C/strass Noivas Festa Casamento Luxo', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/conjunto-colar-e-brinco-removebg-preview.png?raw=true', 5),
           ('Joia De Festa', 339, 'Conjunto Colar E Brincos De Luxo Folheado Cristal Zircônia - Noiva, Debutante, Madrinha- Pronta Entrega', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/joia-de-festa-removebg-preview.png?raw=true', 5),
           ('Conjunto Cristal Azul', 99, 'Delicado Colar + Brinco + Pulseira', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/conjunto-cristal-azul-removebg-preview.png?raw=true', 5),
           ('Blusa Moletom', 122, 'Blusa Moletom Quadribol Grifinória Harry Potter + Brinde', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/blusa-quadriball-removebg-preview.png?raw=true', 4),
           ('Terno Masculino', 198.09, 'Terno Masculino Slim Paletó + Calça 2 Botões Corte Italiano', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/terno-masculino-removebg-preview.png?raw=true', 4),
           ('Jaqueta Puma', 189.9, 'Jaqueta Puma Rtg Fz', 'https://github.com/PedroMoreiraDev/checkpointintegrador-back/blob/main/src/main/resources/images-products/images.png/jaqueta-puma-removebg-preview.png?raw=true', 4)


